Adding fortran wrapper for ex_put_partial_var
sandialabs/seacas pull request #321
Opened 2022-07-06 14:17 UTC by bourdin

This is not ready for inclusion. @gsjaardema can you help me figure out why the wrapper expo does not show up in `libexoIIv2for.a`?

2022-07-06 14:18 UTC, bourdin commented
I have read the CLA Document and I hereby sign the CLA

2022-07-06 14:49 UTC, bourdin commented
Duh, that is what exo_jack_32.c is for... Going back to work!

2022-07-06 14:58 UTC, gsjaardema reviewed
A few changes in the addrwrap.F needed...

2022-07-06 14:58 UTC, gsjaardema commented on packages/seacas/libraries/exodus_for/src/addrwrap.F
> +		obj_id4       = obj_id
Don't need `obj_id4`

2022-07-06 14:58 UTC, gsjaardema commented on packages/seacas/libraries/exodus_for/src/addrwrap.F
> +        CALL exppv4(idexo, time_step, var_type, var_index,
This needs `CALL exppv4(idexo4, time_step4, var_type4, var_index4, obj_id, start_index, num_entities, var_vals, ierr4)`

2022-07-06 14:58 UTC, gsjaardema commented on packages/seacas/libraries/exodus_for/src/addrwrap.F
> +		num_entities4 = num_entities
`start_index` and `num_entities` are 64-bit integers in the C API, so don't need the `4` variants of these.

2022-07-06 14:59 UTC, gsjaardema commented
Yes, there is code duplication between `exodus_for` and `exoIIv2for32` ...

2022-07-07 18:33 UTC, gsjaardema requested changes
Looks good.  The only issue I saw was with the `obj_id`.  Thanks for doing this

2022-07-07 18:33 UTC, gsjaardema commented on packages/seacas/libraries/exodus_for/src/addrwrap.F
> +		obj_id4       = obj_id
`obj_id` should be of type `ex_entity_id` which is an `int64_t`, so it should be passed directly through.

2022-07-07 20:43 UTC, gsjaardema approved these changes

2022-07-07 21:27 UTC, gsjaardema commented
Yes, I have thought about that a few times, but never had time to do or learn more about them.  Would definitely welcome a PR with that improvement...

I'm not sure how the 8-byte real and int compiler option that we use for fortran interacts with those; hopefully not an issue.

2022-07-07 21:28 UTC, merged

2022-07-07 21:28 UTC, gsjaardema commented
Thanks.  Very much appreciated.